language: php
sudo: false

php:
  - 7.1

before_script:
  - composer selfupdate
  - composer install -o --dev --no-interaction
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_success:
  - vendor/bin/coveralls
